In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset= pd.read_csv(r"C:\Users\Gurdeep\Desktop\DATA SCIENTIST\DATA IS GOOD\Internship Unmessenger\Assignments\Assignment 7\car data.csv")

In [3]:
dataset.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [5]:
# checking missing values

dataset.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [6]:
dataset.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [7]:
#checking the categorical data

In [8]:
dataset['Fuel_Type'].value_counts()

Petrol    239
Diesel     60
CNG         2
Name: Fuel_Type, dtype: int64

In [9]:
dataset['Seller_Type'].value_counts()

Dealer        195
Individual    106
Name: Seller_Type, dtype: int64

In [10]:
dataset['Transmission'].value_counts()

Manual       261
Automatic     40
Name: Transmission, dtype: int64

In [11]:
# Encoding the categorical data

dataset.replace({'Fuel_Type': {'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)
dataset.replace({'Seller_Type': {'Dealer':0,'Individual':1}},inplace=True)
dataset.replace({'Transmission': {'Manual':0,'Automatic':1}},inplace=True)

In [12]:
dataset.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0     ritz  2014           3.35           5.59       27000          0   
1      sx4  2013           4.75           9.54       43000          1   
2     ciaz  2017           7.25           9.85        6900          0   
3  wagon r  2011           2.85           4.15        5200          0   
4    swift  2014           4.60           6.87       42450          1   

   Seller_Type  Transmission  Owner  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0

In [13]:
#Extract features and target variable

X=dataset.drop(['Car_Name','Selling_Price'],axis=1)
y=dataset['Selling_Price']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# Split the data into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
#Feature scaling

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Model Selection

## KNN algorithm

In [18]:
from sklearn.neighbors import KNeighborsRegressor

In [19]:
# KNN is a simple and intuitive algorithm that can be used for both regression and classification problems.
# In the context of predicting car prices, it's typically a regression problem.
# because we want to estimate a continuous numerical value ('Selling_Price') based on input features.

In [20]:
# Define the model

knn = KNeighborsRegressor(n_neighbors=5)

In [21]:
# Train the KNN model

knn.fit(X_train,y_train)

KNeighborsRegressor()

In [22]:
# Make predictions on the test set

knn_y_pred = knn.predict(X_test)

In [23]:
knn_y_pred

array([ 0.396,  9.548,  4.58 ,  0.44 ,  6.95 ,  6.36 ,  0.858,  0.63 ,
        0.83 ,  5.58 , 11.126,  0.454,  6.94 ,  1.516,  5.78 ,  3.33 ,
        0.64 , 10.668,  0.746,  1.11 ,  0.664,  9.15 ,  4.44 ,  2.71 ,
        0.506,  3.4  ,  4.82 ,  2.54 ,  0.862,  0.692,  0.674, 10.   ,
        0.476,  2.24 ,  8.44 ,  4.03 ,  5.85 ,  3.96 ,  2.88 ,  5.9  ,
        2.38 ,  3.06 ,  4.41 ,  0.462,  5.85 ,  0.454,  8.08 ,  5.59 ,
        3.13 ,  4.58 ,  5.04 ,  1.086, 23.548, 23.55 ,  8.26 ,  7.66 ,
        5.08 ,  9.83 ,  2.24 ,  6.33 ,  0.504])

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [25]:
# Evaluate the model

print(f"KNN Mean Absolute Error: {mean_absolute_error(y_test, knn_y_pred)}")
print(f"KNN Mean Squared Error: {mean_squared_error(y_test, knn_y_pred)}")
print(f"KNN R2 Score: {r2_score(y_test, knn_y_pred)}")

KNN Mean Absolute Error: 0.6462950819672132
KNN Mean Squared Error: 1.2978898360655742
KNN R2 Score: 0.9436571780966806


## Decision Tree algorithm

In [26]:
from sklearn.tree import DecisionTreeRegressor

In [27]:
# In the context of car prices, this can help in attributing the importance of different features to the final price prediction.
# Decision tree algorithms are relatively easy to implement and understand
# making them a good choice for tasks where model interpretability is important.

In [28]:
# Define the model

dec_tree= DecisionTreeRegressor(random_state=5)

In [29]:
# Train the Decision Tree model

dec_tree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=5)

In [30]:
# Make predictions on the test set

dec_tree_y_pred= dec_tree.predict(X_test)

In [31]:
dec_tree_y_pred

array([ 0.5 , 11.45,  4.1 ,  0.2 ,  7.05,  6.45,  1.11,  0.5 ,  0.48,
        7.2 ,  7.25,  1.25,  6.7 ,  0.45,  4.75,  2.35,  1.05, 14.25,
        0.48,  1.45,  0.25,  8.75,  4.5 ,  2.35,  0.45,  2.9 ,  5.25,
        3.1 ,  1.15,  1.11,  0.25, 11.25,  0.45,  2.25,  7.75,  4.4 ,
        5.85,  5.9 ,  2.55,  5.9 ,  3.49,  3.35,  5.25,  0.6 ,  6.75,
        0.65,  8.5 ,  4.35,  3.1 ,  2.95,  4.75,  1.65, 23.  , 20.75,
        6.45,  9.15,  5.25,  7.75,  2.65,  6.4 ,  0.25])

In [32]:
# Evaluate the model

print(f"Decision Tree Mean Absolute Error: {mean_absolute_error(y_test, dec_tree_y_pred)}")
print(f"Decision Tree Mean Squared Error: {mean_squared_error(y_test, dec_tree_y_pred)}")
print(f"Decision Tree R2 Score: {r2_score(y_test, dec_tree_y_pred)}")

Decision Tree Mean Absolute Error: 0.7
Decision Tree Mean Squared Error: 1.0580491803278689
Decision Tree R2 Score: 0.9540689241292785


## SVM algorithm

In [33]:
from sklearn.svm import SVR

In [34]:
# SVM can capture both linear and non-linear relationships between features and the target variable. 
# SVM can use different kernel functions to handle non-linear relationships effectively.

In [35]:
# Define the model

svm = SVR(kernel='linear')

In [36]:
# Train the SVM model

svm.fit(X_train,y_train)

SVR(kernel='linear')

In [37]:
# Make predictions on the test set

svm_y_pred=svm.predict(X_test)

In [38]:
svm_y_pred

array([ 1.51115832,  8.43269782,  5.53929205, -0.54575108, 10.02593623,
        6.09907155,  0.9745362 ,  0.62273247,  0.83157167,  6.37320773,
        7.54696004,  0.48361806,  7.94378848,  1.89375636,  5.88475767,
        2.99182941,  0.59476411, 11.17314008,  1.09355356,  1.79250733,
        0.29835408,  6.75215216,  5.77998607,  2.99875909,  0.52958226,
        3.97819256,  5.55060786,  3.1566878 ,  1.53502412,  1.27404251,
        0.29190626,  8.23009835, -0.36778502,  3.09706118,  7.23824353,
        4.51263684,  7.79390019,  8.97453887,  2.81975373,  9.25911592,
        5.5604346 ,  4.90279355,  4.35349156,  0.29226105,  6.02268455,
        0.35808611,  7.74919316, 11.88260045,  3.14795633,  4.31017491,
        6.23197042,  1.59502804, 20.25311964, 15.70665888,  6.17234946,
        9.01238206,  4.34667966,  7.7192984 ,  2.95633451,  6.61343949,
        0.06725089])

In [39]:
# Evaluate the model

print(f"SVM Mean Absolute Error: {mean_absolute_error(y_test, svm_y_pred)}")
print(f"SVM Mean Squared Error: {mean_squared_error(y_test, svm_y_pred)}")
print(f"SVM R2 Score: {r2_score(y_test, svm_y_pred)}")

SVM Mean Absolute Error: 1.2839203310368232
SVM Mean Squared Error: 4.251066404080533
SVM R2 Score: 0.8154565428832031


## Comparing R2 Score of all the three algorithm

In [40]:
print(f"KNN R2 Score: {r2_score(y_test, knn_y_pred)}")
print(f"Decision Tree R2 Score: {r2_score(y_test, dec_tree_y_pred)}")
print(f"SVM R2 Score: {r2_score(y_test, svm_y_pred)}")

KNN R2 Score: 0.9436571780966806
Decision Tree R2 Score: 0.9540689241292785
SVM R2 Score: 0.8154565428832031


## Analysing R2 Score of all the three algorithm

In [41]:
# R-squared measures the proportion of the variance in the target variable (Selling_Price) that is explained by the model.
# It provides a measure of how well the independent variables explain the variability in the dependent variable (Selling_Price).

In [42]:
# R2 Score ranges from 0 to 1
# where 0 indicates that the model explains none of the variance, and 1 indicates that the model explains all the variance.
# Higher R2 Score values indicate a better fit of the model to the data.

## Since R2 Score of "Decision Tree" model is the highest and closest to 1. 
## Therefore, Decision Tree is the better-performing model.